### ISSUE TITLE
Some images on docs are not secure (not using https)

### ISSUE THREAD

**Issue by exoego** [fomantic/Fomantic-UI-Docs#114]
One example is http://oi66.tinypic.com/2zr2ckk.jpg on
https://fomantic-ui.com/introduction/new.html#arrow-aligment-on-small-popups

Browsers give warnings in the URL bar.
I am afraid that users see fomantic-ui.com as an insecure site.
![image](https://user-images.githubusercontent.com/127635/55692537-0f8fab00-59e4-11e9-941a-74f35344ea59.png)

According to [MDN](https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content) and [Google Developers](https://developers.google.com/web/fundamentals/security/prevent-mixed-content/what-is-mixed-content?hl=en), such insecure images are not severe issue.
However, attacker may replace insecure images with offensive ones or something like that, so it may injure a reputation of Fomantic.

I think it is good to find free-for-usage & secure (https) image hosting and switch over.

**Comment by lubber-de** [comment]
@hammy2899 Let's adress this for the v.2.8.0 release :wink:

**Comment by lubber-de** [comment]
The images dot not even exist anymore
![image](https://user-images.githubusercontent.com/18379884/68952145-a5cc5080-07bf-11ea-9f5f-ce45d41c9b66.png)

**Comment by lubber-de** [comment]
Fixed by #276
