### ISSUE TITLE
Opening a page using a non-existing anchor leads into wrong rendered code

### ISSUE THREAD

**Issue by lubber-de** [fomantic/Fomantic-UI-Docs#135]
## Bug Report

[Edit] the search engine part of this issue is fixed, so I left the wrong render problem only. 

If a page is called using non-existing anchors  it looks like this
https://fomantic-ui.com/behaviors/form.html#toc
![image](https://user-images.githubusercontent.com/18379884/59196639-7faae080-8b8f-11e9-80f4-5ef0b3b7267b.png)

vs
https://fomantic-ui.com/behaviors/form.html
![image](https://user-images.githubusercontent.com/18379884/59196676-981afb00-8b8f-11e9-8dda-e506565805b4.png)

**Comment by hammy2899** [comment]
This most likely needs to be raised here https://github.com/algolia/docsearch-configs

**Comment by lubber-de** [comment]
@hammy Will do. However, the rendered page should still work even if a non-existing anchor is part of the URL. (somehow the JS code which will turn the raw code into nicely class components is not triggered then.

**Comment by lubber-de** [comment]
Raised an issue here https://github.com/algolia/docsearch-configs/issues/883
In the meantime: Could you please checkout our config (which only you have access to (don't you), because i could not find any algolia related config in the docs repo (?))
The only similar issue i found was https://github.com/algolia/docsearch-configs/issues/570

**Comment by lubber-de** [comment]
😎 They changed our config , but we need to wait until the next page scan

**Comment by lubber-de** [comment]
Search is working now. We should headt to impleemnt the widget within the docs as well now. Will create another issue for that

**Comment by lubber-de** [comment]
Fixed by #285
