### ISSUE TITLE
Duplicate anchor id

### ISSUE THREAD

**Issue by flawyte** [fomantic/Fomantic-UI-Docs#142]
Page : https://fomantic-ui.com/collections/table.html

Both the `States > Colored` and `Variations > Colored` headings have the same id, so when you click on `Variations > Colored` in the floating TOC on the right, it scrolls to `States > Colored`.

**Comment by lubber-de** [comment]
Thanks for reporting
Fixed by #143

**Comment by lubber-de** [comment]
Release in 2.7.7
