### ISSUE TITLE
Search for checkbox doesn't have correct path

### ISSUE THREAD

**Issue by GammaGames** [fomantic/Fomantic-UI-Docs#155]
The page for checkboxes doesn't have the correct path. It links to `checkbox.html#example`, when the link should be `checkbox.html#/examples`. I assume the "correct" path is a bug, because all other pages I've checked use the `[module].html#example` format.

**Comment by lubber-de** [comment]
🤔 Where do you see that wrong link? The current docs v2.7.7 page https://fomantic-ui.com/modules/checkbox.html correctly links to the #/examples page when clicking on the examples-tab

**Comment by GammaGames** [comment]
Huh, were the search results updated recently? I had a gif but I can't seem to find it now and I'm unable to recreate it. When I would search for "checkbox example" on the landing page it would link to https://fomantic-ui.com/modules/checkbox.html#example instead of `#/examples`. Feel free to close if you can't find it either

**Comment by lubber-de** [comment]
Yes, algolia fixed some search issues, when we raised an issue for the search results (i recognized a similiar issue at that time). See https://github.com/algolia/docsearch-configs/issues/883
So, i am closing this as i also cannot find the wrong links anymore
