### ISSUE TITLE
Strange grid example or documentation

### ISSUE THREAD

**Issue by 271ch** [fomantic/Fomantic-UI-Docs#163]
Here:
https://fomantic-ui.com/collections/grid.html#responsive-width

There is this example:
![image](https://user-images.githubusercontent.com/56249288/67697626-252ce800-f9a9-11e9-8ab8-a2479860c0ec.png)

If this line
```
four wide two wide large screen one wide widescreen column
````
has no error, what does it mean putting both `four wide` and `two wide` in front of `large screen`?

**Comment by lubber-de** [comment]
- The `four wide` is used as the default on all screens 
- The `two wide` needs to be seen (and only works) together with the following `large screen` and is used when the window reached a sizer for screen width of max 1200px
- The `one wide widescreen` is used when the sceen width is larger than 1200px
