### ISSUE TITLE
Nag is not on ToC

### ISSUE THREAD

**Issue by exoego** [fomantic/Fomantic-UI-Docs#182]
A page for Nag module exists
https://fomantic-ui.com/modules/nag.html 

But it is not in table of contents.
![image](https://user-images.githubusercontent.com/127635/69034706-47081080-0a25-11ea-94f9-17fbb779e0b5.png)

**Comment by hammy2899** [comment]
This is because nag isn't really supported, it wasn't ever finished.

**Comment by lubber-de** [comment]
But it's at least working in the current state (i am using it at https://rasterbuster.lubber.de) 😄 
![image](https://user-images.githubusercontent.com/18379884/69035182-51091f80-09e3-11ea-9f13-66c4ecb27f7c.png)

Enhancing and cleaning up the nag module is something i have on my todo list already

**Comment by exoego** [comment]
OK...
Then how about mark `nag` as beta/experimental module on ToC, as `toast` or others were used to be ?

**Comment by hammy2899** [comment]
@lubber-de If that's something you want to take care of go ahead but I don't think it's used by many people however I could be wrong.

**Comment by lubber-de** [comment]
Implemented by #257
