### ISSUE TITLE
How to exclude components on custom build is unclear

### ISSUE THREAD

**Issue by exoego** [fomantic/Fomantic-UI-Docs#183]
To reduce the size of `semantic(.min).css` and build time, I would like to remove some unused components from my custom builds.

I browsed the below documents, but those do not mention cleary how to exclude components.
Are there any documents regarding about how to exclude components on custom build?
https://fomantic-ui.com/introduction/build-tools.html
https://fomantic-ui.com/usage/theming.html

I tried below attempts, which failed.

1. Add `components` which contains only used components in `semantic.json` then `guil build` (failed !!)
2. Comment out components in `theme.config` something like `//@ad     : 'default';` then `gulp build` (failed !!)

I think adding a dedicated section for component exclusion is helpful.

**Comment by lubber-de** [comment]
Indeed. Both of your mentioned approaches should work 🤔

**Comment by lubber-de** [comment]
@exoego 
- Did you try `gulp clean` before running `gulp build`
- Did you try to run `npx gulp build`?

**Comment by lubber-de** [comment]
The docs got a more detailed explanation by #203 
https://fomantic-ui.com/introduction/build-tools.html#excluding-components-from-main-cssjs-file

I tested this again and it works for me using `npx gulp build` or `yarn build`. 
So, if you still face this issue, please test using 2.9.0 and in case it still happens to your, provide more error details. Closing until then 🙂
