### ISSUE TITLE
Popup not shown on Pre-existing example

### ISSUE THREAD

**Issue by exoego** [fomantic/Fomantic-UI-Docs#186]
https://fomantic-ui.com/modules/popup.html#pre-existing

I expected a popup shown when hovering on a "Watchmen" card, but popup did not show up.

* Firefox 71.0

**Comment by lubber-de** [comment]
🤔 Cannot reproduce using browserstack...
![popup_firefox](https://user-images.githubusercontent.com/18379884/70418529-dbcdbf00-1a63-11ea-9b6d-b9ec17080478.gif)

**Comment by exoego** [comment]
Oh... problem resolved on my end.
Maybe some cache issue ??

**Comment by lubber-de** [comment]
Maybe you scrolled to far, so the card was too close to the upper edge. In this case the popup appears at the bottom of the card , which was probably not recognized
