### ISSUE TITLE
Docs broken with latest Docpad Release

### ISSUE THREAD

**Issue by RedhatPH8** [fomantic/Fomantic-UI-Docs#192]
Latest release of DOCPAD does not work with current docs. Docpad is deprecated. 
See Semantic-UI ticket: https://github.com/Semantic-Org/Semantic-UI-Docs/issues/404

**Comment by mcverter** [comment]
Please update the README page to indicate the particular version of docpad.

**Comment by exoego** [comment]
Thanks for notifying deprecation of DocPad.

FUI maintainers will eventually consider tool migration.
I found a nice curator of static site generators for this consideration.
https://www.staticgen.com/

**Comment by balupton** [comment]
From https://github.com/Semantic-Org/Semantic-UI-Docs/issues/404#issuecomment-573163065

> For Semantic UI, I'd suggest just going all in on React, with Gatsby or Next as the generator. Or if you care about generic use, then Stencil by Ionic is precisely for design systems like Semantic UI.

(creator of DocPad here, also author of https://staticsitegenerators.net)

**Comment by lubber-de** [comment]
I finally adjusted the docs configuration so it runs using latest docpad 🙂 by #412
