### ISSUE TITLE
[Calendar] add time picker examples

### ISSUE THREAD

**Issue by hammy2899** [fomantic/Fomantic-UI-Docs#22]
Add some examples of the time picker

```javascript
$('.ui.calendar').calendar({
  type: 'time'
});
```

**Comment by prudho** [comment]
[Like this one ?](https://fomantic-ui.com/modules/calendar.html#time-calendar)

**Comment by hammy2899** [comment]
We need more examples to show it off a little more.

**Comment by lubber-de** [comment]
What else do you suggest we need to show off additionally?

For time related input we now have:

https://fomantic-ui.com/modules/calendar.html#time-calendar
https://fomantic-ui.com/modules/calendar.html#24-hour-format
https://fomantic-ui.com/modules/calendar.html#hours
https://fomantic-ui.com/modules/calendar.html#custom-format

**Comment by lubber-de** [comment]
Closing for now. Whoever thinks of more examples, please tell here ;)
