### ISSUE TITLE
[Doc] Tab documentation page should describe about disabled tab

### ISSUE THREAD

**Issue by jamessampford** [fomantic/Fomantic-UI-Docs#238]
I've yet to find a way to disable/deactivate a single tab with the existing functionality, and not too sure whether this should really be a bug, however, it is undocumented so thinking a feature

I propose that disabled is supported and clicking on a disabled tab does not apply a border (by means of applying the `active` class to the tab) and nor does it transition to the attached contents/segment. The current active tab should also not change, for example, first is active, if I click on the second tab, first should still be active

	<div class="ui top attached tabular menu">
		<a class="item active" data-tab="first">First</a>
		<a class="item disabled" data-tab="second">Second (Disabled)</a>
		<a class="item" data-tab="third">Third</a>
	</div>
	<div class="ui bottom attached tab segment active" data-tab="first">
		First
	</div>
	<div class="ui bottom attached tab segment" data-tab="second">
		Second (Disabled so not viewable)
	</div>
	<div class="ui bottom attached tab segment" data-tab="third">
		Third
	</div>

This could potentially be used for some scenarios when a system feature is not turned on within a different tab or some kind of setting elsewhere, but it is wanted to be displayed to show it isn't available in the current view (but may exist in similar views)

**Comment by lubber-de** [comment]
This is now covered by #275  because the tabs use `menu item`
