### ISSUE TITLE
Remote request seems to be broken

### ISSUE THREAD

**Issue by dutrieux** [fomantic/Fomantic-UI-Docs#315]
The remote request seems to be broken on this page : https://fomantic-ui.com/modules/dropdown.html#return-all-choices-remotely
![image](https://user-images.githubusercontent.com/1622751/142731056-ed753477-f38b-4315-b1f6-9e50efd061f1.png)

![image](https://user-images.githubusercontent.com/1622751/142731008-17c976c8-0da3-4918-8429-98ddd0bf8744.png)

**Comment by lubber-de** [comment]
Fixed by #368
