### ISSUE TITLE
Improve html/head title

### ISSUE THREAD

**Issue by mvorisek** [fomantic/Fomantic-UI-Docs#384]
please append ` Docs` to the html title, currently, docs pages are not hinted when something like "fomantic docs" is typed in the browser address bar

example: https://fomantic-ui.com/elements/container.html

actual html title: `Container | Fomantic-UI`

expected html title: `Container | Fomantic-UI Docs`

**Comment by lubber-de** [comment]
Added accordingly in #383

**Comment by mvorisek** [comment]
it seems homepage title is special - https://fomantic-ui.com/

**Comment by lubber-de** [comment]
> it seems homepage title is special - https://fomantic-ui.com/

Yes, this was intentional, as the homepage is planned to provide more than only docs and should reflect "Fomantic-UI" as a whole. For any other docs website the "Docs" was added to its title

> 
> also in Firefox I get in the docs some CORS warnings:
> 
> maybe https://developer.mozilla.org/en-US/docs/Web/Privacy/Storage_access_policy/Errors/CookieBlockedTracker can fix them

i take a look, but _please_ open new issues for different topics. Thanks 🙂
