### ISSUE TITLE
[flyout] cannot close position example on mobile

### ISSUE THREAD

**Issue by jamessampford** [fomantic/Fomantic-UI-Docs#388]
On mobile, when running the example for the position flyout [https://fomantic-ui.com/modules/flyout.html#position] unable to close any of the fly outs, so have to go back in the browser or reload the page. Adding a close button may help? I do wonder if, for these cases, where the developer has not included a close button if one should be injected automatically instead

**Comment by lubber-de** [comment]
>  I do wonder if, for these cases, where the developer has not included a close button if one should be injected automatically instead

I dont think so as the flyout can basically contain any html and does not necessarily need the "modal like" layout and it might be intentional when dimpage: false is used to close the flyout by something else inside the main page

**Comment by lubber-de** [comment]
Fixed by #419
