### ISSUE TITLE
[CI] Setup (travis?) CI to build docs on every PR/commit

### ISSUE THREAD

**Issue by lubber-de** [fomantic/Fomantic-UI-Docs#46]
Setup travis CI or (whatever is needed) to automatically build the docs on every PR/commit, so reviewing makes the life easier.

**Comment by hammy2899** [comment]
We could do this but it wouldn't make reviewing any easier since you wouldn't be able to see the site anywhere.

**Comment by lubber-de** [comment]
Well, the final idea would of course be to generate them somewhere in a separate branch (?) for easy "pull-and-open-index.html" just like the gh_pages...TBH i haven't done this before myself :fearful:

**Comment by hammy2899** [comment]
IMHO I think this would be more effort then pull and building it locally + with the plans to redo the docs this would just be pointless.

**Comment by lubber-de** [comment]
OK, then forget about this for the current situation

**Comment by prudho** [comment]
A solution would be upload artifacts from travis job in a server, maybe an instance or a cheap hosting (mine ? 100gb should be enough for a lot of uploads), and then add a PR comments with a link to the generated files. I'm sure this is doable.

**Comment by hammy2899** [comment]
@prudho Maybe but I feel this is a lot of work for a small problem which is going to be fixed in the future.
