### ISSUE TITLE
Feat: Introduce CDN links for starters

### ISSUE THREAD

**Issue by exoego** [fomantic/Fomantic-UI-Docs#92]
It is very happy that [Fomantic-UI is now hosted on CDNJS](https://cdnjs.com/libraries/fomantic-ui) in addition to [JSDELIVR](https://www.jsdelivr.com/package/npm/fomantic-ui) 😄 

I suggest to add links to those CDN-hosted FUIs in [Getting Started](https://fomantic-ui.com/introduction/getting-started.html) or new dedicated page,  like [jQuery CDN](https://code.jquery.com/) and [Quick Start for Bootstrap](https://www.bootstrapcdn.com/) doing so.

So new comers of FUI can get started very quickly 🚄  and gain performance boost thanks to CDNs🚀, just adding `<link>`  and `<script>` to their HTML, no need to install & build by themselves.

And, perhaps the pre-built distributions may be enough for many users who do not need to customize.

**Comment by hammy2899** [comment]
I will do this when I get some time and I will try and put it live this weekend.

**Comment by hammy2899** [comment]
Added to this page https://fomantic-ui.com/introduction/getting-started.html
