### ISSUE TITLE
metadata.json is missing

### ISSUE THREAD

**Issue by exoego** [fomantic/Fomantic-UI-Docs#94]
* 404 https://fomantic-ui.com/metadata.json
* 200 https://semantic-ui.com/metadata.json

![image](https://user-images.githubusercontent.com/127635/52520922-b856ae00-2cb2-11e9-8050-b3447bb221a7.png)

**Comment by hammy2899** [comment]
This may have occurred when we updated to gulp4.

/cc @ColinFrick

**Comment by exoego** [comment]
Hmm, metada.json now exists but its content is empty (`{}`) .
https://fomantic-ui.com/metadata.json

Is this intended ?

**Comment by RedhatPH8** [comment]
@ColinFrick Was the blank metadata.json intended? Also, I'm trying to understand the point of the file. It looks like it consolidates from each /document/'s metadata, which would explain it being blank here. When I render the document libary, the file only contain's Echo is on. 
I wonder if there is a way we could reverse the process, such that we can update a single document, i.e. metadata.json, and it could parse the document, and apply the metadata back to the appropriate pages. This would allow us to quickly at themes, mass change layouts or css, etc. Thoughts?
