### ISSUE TITLE
Please add link to article about using LESS package

### ISSUE THREAD

**Issue by murbanowicz** [fomantic/Fomantic-UI-Docs#95]
Hello,

As promised - https://medium.com/@marekurbanowicz/how-to-customize-fomantic-ui-with-less-and-webpack-applicable-to-semantic-ui-too-fbf98a74506c

Can you add it to the documentation so people can find it? @hammy2899 @lubber-de

**Comment by hammy2899** [comment]
Added to the bottom of this page https://fomantic-ui.com/introduction/getting-started.html
